---
kind: pipeline
name: default

steps:
- name: check_syntax
  image: hashicorp/packer:light
  commands:
    - wget https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.linux
    - packer validate vcenter-centos7.json
    - packer validate vcenter-centos7mod.json
    - packer validate vcenter-centos8.json
