---
kind: pipeline
name: default

steps:
- name: check syntax
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - wget https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.linux
    - packer validate vcenter-centos7.json
    - packer validate vcenter-centos8.json
    - packer validate vcenter-debian10.json

- name: upload kickstart
  image: plugins/s3
  settings:
    endpoint: https://oos.eu-west-2.outscale.com
    bucket: homelab
    access_key:
      from_secret: s3_access_key
    secret_key:
      from_secret: s3_secret_key
    source: kickstart/*
    strip_prefix: kickstart/
    target: /packer_ks
    acl: public-read

- name: build centos7
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - packer build vcenter-centos7.json
  depends_on: [ 'check syntax' ]

- name: build centos8
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - packer build vcenter-centos8.json
  depends_on: [ 'check syntax', 'upload kickstart' ]

- name: build debian10
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - packer build vcenter-debian10.json
  depends_on: [ 'check syntax', 'upload kickstart' ]
