---
kind: pipeline
name: default

steps:
- name: check syntax
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - wget https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.linux
    - packer validate vcenter-centos7.json
    - packer validate vcenter-centos7mod.json
    - packer validate vcenter-centos8.json

- name: upload kickstart
  image: plugins/s3
  settings:
    endpoint: https://s3.lecat.pro
    bucket: tmp
    access_key:
      from_secret: s3_access_key
    secret_key:
      from_secret: s3_secret_key
    source: kickstart/*
    target: /kickstarts
    acl: public

- name: build centos 7
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - wget https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.linux
    - packer build vcenter-centos7.json
  depends_on: [ 'check syntax' ]

- name: build centos 8
  image: hashicorp/packer:light
  environment:
    VCENTER_HOST:
      from_secret: vcenter_host
    VCENTER_USER:
      from_secret: vcenter_user
    VCENTER_PASSWORD:
      from_secret: vcenter_password
  commands:
    - wget https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.linux
    - packer build vcenter-centos8.json
  depends_on: [ 'check syntax' ]
