stages:
  - preparation
  - build

upload_ks:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  stage: preparation
  script:
    - aws --endpoint https://oos.eu-west-2.outscale.com s3 cp ./kickstart s3://homelab/packer_ks --acl public-read --recursive

check_conf:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: preparation
  script:
    - packer init -upgrade vcenter-windows.pkr.hcl 
    - packer validate vcenter-rocky8.pkr.hcl
    - packer validate vcenter-rhel8.pkr.hcl
    - packer validate vcenter-ubuntu2004.pkr.hcl
    - packer validate vcenter-windows.pkr.hcl
    - packer validate vcenter-windows11.pkr.hcl

build_rocky8:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: packer build -force vcenter-rocky8.pkr.hcl

build_rhel8:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: packer build -force vcenter-rhel8.pkr.hcl

build_ubuntu2004:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: packer build -force vcenter-ubuntu2004.pkr.hcl

build_windows:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: 
    - packer init -upgrade vcenter-windows.pkr.hcl
    - packer build -force vcenter-windows.pkr.hcl

build_windows10:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: 
    - packer init -upgrade vcenter-windows11.pkr.hcl
    - packer build -force vcenter-windows11.pkr.hcl