stages:
  - preparation
  - build

upload_ks:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  stage: preparation
  script:
    - aws --endpoint https://oos.eu-west-2.outscale.com s3 cp ./kickstart s3://homelab/packer_ks --acl public-read --recursive

check_conf:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: preparation
  script:
    - packer validate vcenter-centos8.json
    - packer validate vcenter-rhel8.json
    - packer validate vcenter-ubuntu2004.json

build_centos8:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: packer build -force vcenter-centos8.json

build_rhel8:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: packer build -force vcenter-rhel8.json

build_ubuntu2004:
  image:
    name: hashicorp/packer:light
    entrypoint: [""]
  stage: build
  script: packer build -force vcenter-ubuntu2004.json
